USE [master]
GO

/****** Object:  Database [DW_Prueba]    Script Date: 9/4/2025 20:18:28 ******/
CREATE DATABASE [DW_Prueba]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DW_Prueba', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DW_Prueba.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DW_Prueba_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DW_Prueba_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DW_Prueba].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DW_Prueba] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DW_Prueba] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DW_Prueba] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DW_Prueba] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DW_Prueba] SET ARITHABORT OFF 
GO

ALTER DATABASE [DW_Prueba] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DW_Prueba] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DW_Prueba] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DW_Prueba] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DW_Prueba] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DW_Prueba] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DW_Prueba] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DW_Prueba] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DW_Prueba] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DW_Prueba] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DW_Prueba] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DW_Prueba] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DW_Prueba] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DW_Prueba] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DW_Prueba] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DW_Prueba] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DW_Prueba] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DW_Prueba] SET RECOVERY FULL 
GO

ALTER DATABASE [DW_Prueba] SET  MULTI_USER 
GO

ALTER DATABASE [DW_Prueba] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DW_Prueba] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DW_Prueba] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DW_Prueba] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DW_Prueba] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DW_Prueba] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DW_Prueba] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DW_Prueba] SET  READ_WRITE 
GO

